name: Daily Commit

on:
  schedule:
    - cron: '5 19 * * *' # Runs at 12:00 AM UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name 'suhairshareef'
          git config --global user.email 'suhairshareef1999@gmail.com'

      - name: Create and push commit
        run: |
          echo "$(date)" >> daily_commit.txt
          git add .
          git commit -m "Daily commit - $(date)"
          git push
